import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.186.1/build/three.module.js';
import { HERO_IMAGE_URL } from './hero-data.js';
import { FAIL_AUDIO_URL } from './audio-fail.js';
import { FART_AUDIO_URL } from './audio-fart.js';
import { HURT_AUDIO_URL } from './audio-hurt.js';

const W=9,H=16,HW=4.5,HH=8,PX=-1.72,PW=1.075,PH=1.435,HITW=.60,HITH=.78,OW=1.78,OH=11.8;
const GRAV=-15.2,JUMP=5.72,MAX_HP=3,ELECTRIC_SCORE=20;
const shell=document.querySelector('#game-shell'),host=document.querySelector('#canvas-host');
const scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best'),heartsEl=document.querySelector('#hearts');
const finalScoreEl=document.querySelector('#final-score'),finalBestEl=document.querySelector('#final-best');
const startPanel=document.querySelector('#start-panel'),overPanel=document.querySelector('#game-over-panel');
const startBtn=document.querySelector('#start-button'),restartBtn=document.querySelector('#restart-button');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setSize(shell.clientWidth,shell.clientHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-HW,HW,HH,-HH,.1,100);camera.position.z=10;
const obstacleLayer=new THREE.Group(),pickupLayer=new THREE.Group(),fxLayer=new THREE.Group();scene.add(obstacleLayer,pickupLayer,fxLayer);
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function tex(c){const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.generateMipmaps=false;return t}
function rr(x,a,b,w,h,r){x.beginPath();x.roundRect(a,b,w,h,r)}
function outline(x,draw,c='#493b54',w=8){for(let i=0;i<2;i++){x.save();x.translate(rand(-1.4,1.4),rand(-1.4,1.4));x.strokeStyle=i?c+'55':c;x.lineWidth=w-i*3;draw();x.stroke();x.restore()}}

function bgTex(){const c=document.createElement('canvas');c.width=720;c.height=1280;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,0,1280);g.addColorStop(0,'#b9eaff');g.addColorStop(.58,'#e6f8ff');g.addColorStop(1,'#ffd9c9');x.fillStyle=g;x.fillRect(0,0,720,1280);for(const [cx,cy,s] of [[120,170,1],[570,330,.8],[170,780,.7],[590,950,.9]]){x.save();x.translate(cx,cy);x.scale(s,s);x.fillStyle='rgba(255,255,255,.72)';[[-42,5,45],[5,-12,62],[60,8,40]].forEach(([a,b,r])=>{x.beginPath();x.arc(a,b,r,0,Math.PI*2);x.fill()});x.restore()}for(let i=0;i<45;i++){x.fillStyle=['#ff6f8466','#52b8e066','#ffd45866'][i%3];x.beginPath();x.arc(rand(0,720),rand(0,1280),rand(2,6),0,Math.PI*2);x.fill()}return tex(c)}
const bg=new THREE.Mesh(new THREE.PlaneGeometry(W,H),new THREE.MeshBasicMaterial({map:bgTex(),depthWrite:false}));bg.position.z=-8;scene.add(bg);

function obstacleTex(type){const c=document.createElement('canvas');c.width=420;c.height=1500;const x=c.getContext('2d');x.lineJoin=x.lineCap='round';x.shadowColor='rgba(38,28,45,.18)';x.shadowBlur=14;x.shadowOffsetY=7;
 if(type==='pencil'){x.fillStyle='#e6b17d';x.beginPath();x.moveTo(210,8);x.lineTo(80,270);x.lineTo(340,270);x.closePath();x.fill();outline(x,()=>{x.beginPath();x.moveTo(210,8);x.lineTo(80,270);x.lineTo(340,270);x.closePath()});x.fillStyle='#34313d';x.beginPath();x.moveTo(210,8);x.lineTo(177,80);x.lineTo(243,80);x.closePath();x.fill();const g=x.createLinearGradient(80,0,340,0);g.addColorStop(0,'#ffc72e');g.addColorStop(.5,'#fff17a');g.addColorStop(1,'#f39a18');x.fillStyle=g;rr(x,80,250,260,980,30);x.fill();outline(x,()=>rr(x,80,250,260,980,30));x.fillStyle='#c4ccd4';rr(x,80,1210,260,90,18);x.fill();outline(x,()=>rr(x,80,1210,260,90,18),undefined,7);x.fillStyle='#f06478';rr(x,94,1285,232,170,30);x.fill();outline(x,()=>rr(x,94,1285,232,170,30),undefined,7)}
 else if(type==='knife'){const g=x.createLinearGradient(90,0,330,0);g.addColorStop(0,'#abc6dd');g.addColorStop(.5,'#fff');g.addColorStop(1,'#86a2bd');x.fillStyle=g;x.beginPath();x.moveTo(210,8);x.lineTo(335,190);x.lineTo(310,610);x.lineTo(110,610);x.lineTo(85,190);x.closePath();x.fill();outline(x,()=>{x.beginPath();x.moveTo(210,8);x.lineTo(335,190);x.lineTo(310,610);x.lineTo(110,610);x.lineTo(85,190);x.closePath()},'#41536a');for(let y=160;y<560;y+=65){x.strokeStyle='#6f859788';x.lineWidth=4;x.beginPath();x.moveTo(130,y);x.lineTo(290,y+20);x.stroke()}const h=x.createLinearGradient(70,0,350,0);h.addColorStop(0,'#2187c8');h.addColorStop(.5,'#58cdf7');h.addColorStop(1,'#17609f');x.fillStyle=h;rr(x,68,560,284,870,50);x.fill();outline(x,()=>rr(x,68,560,284,870,50),'#304d6b');x.fillStyle='#ffb536';rr(x,135,720,150,140,35);x.fill();outline(x,()=>rr(x,135,720,150,140,35),'#694d2f',7)}
 else{x.fillStyle='#465267';x.beginPath();x.moveTo(210,8);x.lineTo(175,115);x.lineTo(245,115);x.closePath();x.fill();outline(x,()=>{x.beginPath();x.moveTo(210,8);x.lineTo(175,115);x.lineTo(245,115);x.closePath()},'#433c55');x.strokeStyle='#53657a';x.lineWidth=20;x.beginPath();x.moveTo(210,100);x.lineTo(210,1340);x.stroke();const g=x.createLinearGradient(110,0,310,0);g.addColorStop(0,'#7458d0');g.addColorStop(.5,'#b398ff');g.addColorStop(1,'#543caa');x.fillStyle=g;x.beginPath();x.moveTo(210,130);x.quadraticCurveTo(315,300,320,520);x.lineTo(290,1190);x.quadraticCurveTo(210,1260,130,1190);x.lineTo(100,520);x.quadraticCurveTo(105,300,210,130);x.closePath();x.fill();outline(x,()=>{x.beginPath();x.moveTo(210,130);x.quadraticCurveTo(315,300,320,520);x.lineTo(290,1190);x.quadraticCurveTo(210,1260,130,1190);x.lineTo(100,520);x.quadraticCurveTo(105,300,210,130);x.closePath()},'#493f68');x.strokeStyle='#53657a';x.lineWidth=22;x.beginPath();x.moveTo(210,1320);x.lineTo(210,1400);x.quadraticCurveTo(210,1470,135,1450);x.stroke()}
 x.shadowColor='transparent';return tex(c)}
const obstacleTexs={pencil:obstacleTex('pencil'),knife:obstacleTex('knife'),umbrella:obstacleTex('umbrella')},types=Object.keys(obstacleTexs);
function pickupTex(type){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.lineJoin=x.lineCap='round';x.shadowColor='#3b253d44';x.shadowBlur=14;x.shadowOffsetY=7;if(type==='dorayaki'){x.fillStyle='#e89a49';x.beginPath();x.ellipse(128,82,84,45,0,0,Math.PI*2);x.fill();x.fillStyle='#6e292c';rr(x,60,112,136,42,18);x.fill();x.fillStyle='#bd6435';x.beginPath();x.ellipse(128,164,84,45,0,0,Math.PI*2);x.fill();outline(x,()=>{x.beginPath();x.ellipse(128,123,92,87,0,0,Math.PI*2)},'#654239',7)}else{x.fillStyle='#49d85b';rr(x,72,66,112,140,25);x.fill();outline(x,()=>rr(x,72,66,112,140,25),'#2a653c',7);x.fillStyle='#4c5968';rr(x,94,34,68,46,10);x.fill();x.fillStyle='#f3fff0';x.beginPath();x.arc(128,135,38,0,Math.PI*2);x.fill();x.strokeStyle='#235c36';x.lineWidth=10;x.beginPath();x.moveTo(108,116);x.lineTo(148,154);x.moveTo(148,116);x.lineTo(108,154);x.stroke()}return tex(c)}
const pickupTexs={dorayaki:pickupTex('dorayaki'),poison:pickupTex('poison')};
function cloudTex(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle='#ffffffbb';x.strokeStyle='#584a5766';x.lineWidth=4;[[40,70,25],[64,52,31],[88,70,23]].forEach(([a,b,r])=>{x.beginPath();x.arc(a,b,r,0,Math.PI*2);x.fill();x.stroke()});return tex(c)}
function dropTex(color,splat=false){const c=document.createElement('canvas');c.width=c.height=96;const x=c.getContext('2d');x.fillStyle=color;x.strokeStyle='#5d344366';x.lineWidth=4;if(!splat){x.beginPath();x.moveTo(48,8);x.quadraticCurveTo(75,42,70,62);x.arc(48,62,22,0,Math.PI*2);x.fill();x.stroke()}else for(let i=0;i<5;i++){x.beginPath();x.arc(rand(24,72),rand(24,72),rand(8,16),0,Math.PI*2);x.fill();x.stroke()}return tex(c)}
const smokeTex=cloudTex(),bloodTex=dropTex('#e21f3f'),poisonFxTex=dropTex('#42d84d',true);
const playerMat=new THREE.SpriteMaterial({transparent:true,depthTest:false,depthWrite:false}),player=new THREE.Sprite(playerMat);player.position.set(PX,0,3);player.scale.set(PW,PH,1);scene.add(player);new THREE.TextureLoader().load(HERO_IMAGE_URL,t=>{t.colorSpace=THREE.SRGBColorSpace;playerMat.map=t;playerMat.needsUpdate=true});

const sounds={fail:new Audio(FAIL_AUDIO_URL),fart:new Audio(FART_AUDIO_URL),hurt:new Audio(HURT_AUDIO_URL)};sounds.fail.volume=.72;sounds.fart.volume=.9;sounds.hurt.volume=.85;Object.values(sounds).forEach(a=>a.preload='auto');
function sfx(k,v=1){try{const a=sounds[k].cloneNode(true);a.volume=clamp((sounds[k].volume||1)*v,0,1);void a.play()}catch{}}
function toneHeal(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const a=toneHeal.a||(toneHeal.a=new C());if(a.state==='suspended')void a.resume();const n=a.currentTime;[540,700,870].forEach((f,i)=>{const o=a.createOscillator(),g=a.createGain(),d=i*.08;o.frequency.value=f;g.gain.setValueAtTime(.0001,n+d);g.gain.exponentialRampToValueAtTime(.08,n+d+.015);g.gain.exponentialRampToValueAtTime(.0001,n+d+.15);o.connect(g);g.connect(a.destination);o.start(n+d);o.stop(n+d+.17)})}
function zap(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const a=zap.a||(zap.a=new C());if(a.state==='suspended')void a.resume();const n=a.currentTime,l=Math.floor(a.sampleRate*.1),b=a.createBuffer(1,l,a.sampleRate),d=b.getChannelData(0);for(let i=0;i<l;i++)d[i]=(Math.random()*2-1)*(1-i/l);const s=a.createBufferSource(),f=a.createBiquadFilter(),g=a.createGain();s.buffer=b;f.type='highpass';f.frequency.value=950;g.gain.value=.1;s.connect(f);f.connect(g);g.connect(a.destination);s.start(n)}

const smoke=[],particles=[],obstacles=[],pickups=[];let state='ready',score=0,best=Number(localStorage.getItem('flappyTestBest')||0)||0,hp=MAX_HP,vy=0,spawn=.45,readyT=0,pulse=0,invuln=0,gameTime=0,pickupCooldown=2;
bestEl.textContent=best;finalBestEl.textContent=best;function hearts(){[...heartsEl.querySelectorAll('.heart')].forEach((e,i)=>e.classList.toggle('empty',i>=hp))}hearts();
function puff(){const ex=player.position.x-PW*.38,ey=player.position.y-PH*.1;for(let i=0;i<7;i++){const m=new THREE.SpriteMaterial({map:smokeTex,transparent:true,opacity:rand(.4,.7),depthTest:false}),s=new THREE.Sprite(m),z=rand(.14,.25),life=rand(.38,.62);s.scale.set(z,z,1);s.position.set(ex+rand(-.04,.04),ey+rand(-.05,.05),2.6);fxLayer.add(s);smoke.push({s,vx:rand(-2.4,-1.4),vy:rand(-.45,.45),life,max:life,grow:rand(.45,.72)})}}
function burst(kind){const t=kind==='poison'?poisonFxTex:bloodTex,n=kind==='poison'?10:15;for(let i=0;i<n;i++){const m=new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}),s=new THREE.Sprite(m),z=rand(.07,.16),life=rand(.36,.75);s.scale.set(z,z,1);s.position.set(player.position.x+rand(-.15,.15),player.position.y+rand(-.15,.15),4);fxLayer.add(s);particles.push({s,vx:rand(-2.2,2.2),vy:rand(-.5,2.7),life,max:life})}}
function updateFx(dt){for(let i=smoke.length-1;i>=0;i--){const p=smoke[i];p.life-=dt;p.s.position.x+=p.vx*dt;p.s.position.y+=p.vy*dt;const z=p.s.scale.x+p.grow*dt;p.s.scale.set(z,z,1);p.s.material.opacity=.65*Math.max(0,p.life/p.max);if(p.life<=0){fxLayer.remove(p.s);p.s.material.dispose();smoke.splice(i,1)}}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.vy-=4.8*dt;p.s.position.x+=p.vx*dt;p.s.position.y+=p.vy*dt;p.s.material.opacity=Math.max(0,p.life/p.max);if(p.life<=0){fxLayer.remove(p.s);p.s.material.dispose();particles.splice(i,1)}}}
function gap(){return 3.55-Math.min(score*.024,.62)}function speed(){return 3.35+Math.min(score*.055,1.65)}function interval(){return 1.52-Math.min(score*.0075,.21)}
function electric(g,cy){const group=new THREE.Group(),lines=[];for(let j=0;j<3;j++){const geo=new THREE.BufferGeometry(),a=new Float32Array(21*3);geo.setAttribute('position',new THREE.BufferAttribute(a,3));const mat=new THREE.LineBasicMaterial({color:0x29d9ff,transparent:true,opacity:0,depthTest:false}),l=new THREE.Line(geo,mat);l.position.z=2.5;group.add(l);lines.push(l)}obstacleLayer.add(group);return{group,lines,g,cy,off:rand(0,2.8),active:false,warn:false,j:.0,last:'off'}}
function redraw(e){const lo=e.cy-e.g/2+.07,hi=e.cy+e.g/2-.07;e.lines.forEach((l,j)=>{const a=l.geometry.attributes.position.array;for(let i=0;i<21;i++){const t=i/20,k=i*3;a[k]=Math.sin(t*24+gameTime*20+j)*.1+rand(-.09,.09)+(j-1)*.04;a[k+1]=lo+(hi-lo)*t}l.geometry.attributes.position.needsUpdate=true})}
function updateEle(o,dt){const e=o.electric;if(!e)return;e.group.position.x=o.group.position.x;const p=(gameTime+e.off)%2.8;e.warn=(p>=1.3&&p<1.52)||(p>=1.72&&p<1.94);e.active=p>=1.94&&p<2.58;e.lines.forEach((l,i)=>{l.material.color.set(e.active?(i?0x94efff:0x22ceff):0xffc33c);l.material.opacity=e.active?(.96-i*.18):(e.warn?(.64-i*.12):0)});e.j-=dt;if((e.active||e.warn)&&e.j<=0){e.j=e.active?.04:.075;redraw(e)}const s=e.active?'on':e.warn?'warn':'off';if(s==='on'&&e.last!=='on')zap();e.last=s}
function spawnPickup(cy,g,x){if(pickupCooldown>0)return;const r=Math.random(),type=r<.065?'dorayaki':r<.135?'poison':null;if(!type)return;const m=new THREE.SpriteMaterial({map:pickupTexs[type],transparent:true,depthTest:false}),s=new THREE.Sprite(m),z=type==='dorayaki'?.68:.62;s.scale.set(z,z,1);s.position.set(x+rand(.45,1),cy+rand(-g*.18,g*.18),2.2);pickupLayer.add(s);pickups.push({type,s,r:z*.34,b:rand(0,6.28)});pickupCooldown=5.4}
function spawnPair(){const type=types[Math.floor(Math.random()*types.length)],g=gap(),cy=rand(-2.5,2.5),group=new THREE.Group(),bm=new THREE.SpriteMaterial({map:obstacleTexs[type],transparent:true,depthTest:false}),tm=bm.clone();tm.rotation=Math.PI;const b=new THREE.Sprite(bm),t=new THREE.Sprite(tm);b.scale.set(OW,OH,1);t.scale.set(OW,OH,1);b.position.set(0,cy-g/2-OH/2,1);t.position.set(0,cy+g/2+OH/2,1);group.add(b,t);group.position.x=HW+1.45;obstacleLayer.add(group);const e=score>=ELECTRIC_SCORE?electric(g,cy):null;if(e)e.group.position.x=group.position.x;obstacles.push({group,cy,g,scored:false,electric:e});spawnPickup(cy,g,group.position.x)}
function flap(){vy=JUMP;pulse=1;puff();sfx('fart')}
function damage(kind='spike'){if(state!=='playing'||invuln>0||hp<=0)return false;hp--;invuln=.92;hearts();burst(kind==='poison'?'poison':'blood');sfx('hurt');if(kind==='electric')zap();vy=Math.max(vy,kind==='poison'?1.2:2);if(hp<=0)end('hp');return true}
function heal(){if(hp<MAX_HP){hp++;hearts()}toneHeal()}
function end(reason='hp'){if(state!=='playing')return;state='gameover';playerMat.opacity=1;sfx('fail');if(score>best){best=score;localStorage.setItem('flappyTestBest',best)}bestEl.textContent=best;finalScoreEl.textContent=score;finalBestEl.textContent=best;overPanel.querySelector('h2').textContent=reason==='fall'?'掉出画面了':'生命值耗尽';overPanel.classList.add('visible')}
function reset(){for(const o of obstacles){obstacleLayer.remove(o.group);o.group.traverse(n=>n.material?.dispose());if(o.electric){obstacleLayer.remove(o.electric.group);o.electric.lines.forEach(l=>{l.geometry.dispose();l.material.dispose()})}}obstacles.length=0;for(const p of pickups){pickupLayer.remove(p.s);p.s.material.dispose()}pickups.length=0;for(const p of [...smoke,...particles]){fxLayer.remove(p.s);p.s.material.dispose()}smoke.length=particles.length=0;score=0;hp=MAX_HP;invuln=0;vy=0;spawn=.44;gameTime=0;pickupCooldown=2;player.position.set(PX,0,3);playerMat.opacity=1;playerMat.rotation=0;player.scale.set(PW,PH,1);scoreEl.textContent=0;bestEl.textContent=best;hearts()}
function start(){reset();state='playing';startPanel.classList.remove('visible');overPanel.classList.remove('visible');flap()}
function hitO(o){const dx=Math.abs(o.group.position.x-PX);if(dx>=OW*.36+HITW/2)return false;return player.position.y-HITH/2<o.cy-o.g/2||player.position.y+HITH/2>o.cy+o.g/2}
function updatePickups(dt){const sp=speed();for(let i=pickups.length-1;i>=0;i--){const p=pickups[i];p.s.position.x-=sp*dt;p.b+=dt*4.2;p.s.position.y+=Math.sin(p.b)*.0025;p.s.material.rotation=Math.sin(p.b*.7)*.08;const dx=p.s.position.x-PX,dy=p.s.position.y-player.position.y;if(dx*dx+dy*dy<(p.r+HITW*.35)**2){p.type==='dorayaki'?heal():damage('poison');pickupLayer.remove(p.s);p.s.material.dispose();pickups.splice(i,1);continue}if(p.s.position.x<-HW-1){pickupLayer.remove(p.s);p.s.material.dispose();pickups.splice(i,1)}}}
function update(dt){gameTime+=dt;pickupCooldown=Math.max(0,pickupCooldown-dt);invuln=Math.max(0,invuln-dt);playerMat.opacity=invuln>0&&Math.floor(invuln*16)%2?.34:1;vy+=GRAV*dt;player.position.y+=vy*dt;playerMat.rotation=THREE.MathUtils.lerp(playerMat.rotation,THREE.MathUtils.clamp(vy*.055,-.56,.28),.14);pulse=Math.max(0,pulse-dt*6);const q=1+pulse*.055;player.scale.set(PW/q,PH*q,1);spawn+=dt;if(spawn>=interval()){spawn=0;spawnPair()}const sp=speed();for(let i=obstacles.length-1;i>=0;i--){const o=obstacles[i];o.group.position.x-=sp*dt;updateEle(o,dt);if(!o.scored&&o.group.position.x<PX){o.scored=true;score++;scoreEl.textContent=score}if(hitO(o)){if(damage('spike'))player.position.y+=player.position.y>o.cy?-.12:.12}else if(o.electric?.active){const dx=Math.abs(o.group.position.x-PX),inside=player.position.y>o.cy-o.g/2&&player.position.y<o.cy+o.g/2;if(dx<HITW*.55+.18&&inside)damage('electric')}if(o.group.position.x<-HW-1.9){obstacleLayer.remove(o.group);o.group.traverse(n=>n.material?.dispose());if(o.electric){obstacleLayer.remove(o.electric.group);o.electric.lines.forEach(l=>{l.geometry.dispose();l.material.dispose()})}obstacles.splice(i,1)}}updatePickups(dt);if(player.position.y-HITH/2<-HH-.12){end('fall');return}if(player.position.y+HITH/2>HH-.06){player.position.y=HH-HITH/2-.08;vy=Math.min(vy,-2.5)}}
function action(){if(state==='ready'||state==='gameover')start();else flap()}
startBtn.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();start()});restartBtn.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();start()});shell.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;e.preventDefault();action()});window.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();action()}});window.addEventListener('resize',()=>{renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setSize(shell.clientWidth,shell.clientHeight,false)});
const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),1/30);if(state==='ready'){readyT+=dt;player.position.y=Math.sin(readyT*2.15)*.2;playerMat.rotation=Math.sin(readyT*1.25)*.03}else if(state==='playing')update(dt);updateFx(dt);renderer.render(scene,camera)});
